
[preface]

== Preface

 - [ ] How I will treat the content
 - [ ] What will I use, why am I using them (tools, approach, how different from OCJP)
 - [ ] What I will cover, what I will not cover
 - [ ] What the typography means, and the admonitions
 
 
=== Choice of tools

This book is aimed at beginning Java programmers. Java shares a lot in common with languages like C, C++ and C#. When you go down the route of C#.NET programming, most likely, you will use the Microsoft tool chain, Visual Studio.NET. Why wouldn’t you? VS is an excellent tool. There are programmers who code in C# and do not use Visual Studio. Granted. But an overwhelming number of these programmers use VS on Windows rather than Mono on Linux or OSX. For these programmers, a lot of decisions on their programming ecosystem have already been made. There is no need to make decision on which programming editor to use. Sadly, that is not the case with Java. 

You can build Java applications with or without an integrated development environment (IDE) like Visual Studio. You simply need to get the Java development kit properly installed, configure your system path and choose an editor. If you do decide to use an IDE, you may choose either Eclipse, Netbeans or IntelliJ. There are other IDEs but these three that I mentioned are probably the most popular ones. 

I wanted to focus on the programming part, not the tools. So I decided on a very spartan route. 


1. **Basic programmer’s editor**. All of the code examples appearing in the book were written and tested using a basic programmer’s editor, Sublime Text 3, if you are interested. You don’t need to use the same in order to follow the coding examples. Any decent programmer’s editor will do e.g. TextMate (Mac), Notepad++ (Windows), gEdit (Linux), Emacs (Multiplatform) or Vi (Multiplatform).
2. **Command Line Interface**. Hello, is it me your looking for


=== Typography


`monospace text`::
These types of text sometimes appear in a block and sometimes inline within sentences, `like this`. When you see them inline, I am simply indicating that the word or group of words are part of a program. You don’t need to type the words appearing as `inline monospace`. They are there to simply highlight words that are part of a program.

+
As an example, you may see it like this.
+
> When a java program is started, the runtime will look for the
> function `public static void main(String args[])`, this is the
> entry point of all Java applications.

`monospace in block`::
Monospace text inside a block are either a full listing of a program, snippets of a program or sequences of commands that are supposed to be entered on a terminal shell. Either way, you will need to type these kinds of text. Block monospace text are easy to spot because they are usually labeled as program listing. Some examples are shown below.
+
.Listing 1-1, Boiler plate code for background processing
----
class RunInBackground implements Runnable {
  public void run() {
    // Do somethings in the background thread
  }
}
----
+
.Listing 1-2, Create a working directory, Windows
----
mkdir \Users\yourUserName\myproject
cd \Users\yourUserName\myproject
dir
----

`remarked monospace`::
This is the same as monospace in block but this one has callouts . The code is marked with callout numbers and the callouts appear as a bulleted list immediately after block listing. These kinds of text appear when I am walking you through the codes. This comes after you have already typed the code exercises. It is just meant to explain some points further.  It looks like the the following code:
+
.Listing1 1-3
----
class RunInBackground 
    implements //<1> 
    Runnable { //<2>
      public void run() { //<3>
        // Do somethings in the background thread <4>
        }
      }
----
<1> `implements` means inherit from an interface, not a class
<2> `Runnable` interface 
<3> The only method to override in Runnable
<4> This is where background magic happens

=== Admonitions

WARNING: Read this section slowly and follow the directions of the exercise to the letter. If you don’t, you will most likely encounter some errors

Warnings are usually given

TIP: Some extra tidbits of knowledge that are nice to know but not absolutely necessary. It’s okay to ignore these tips but they usually adds some trivial knowledge to the topic

NOTE: This sidebar usually offers some insight as to what’s going on behind the scenes. Sometimes they may even offer some explanation to some commands or why some commands behave they way they do

CAUTION: Read this section slowly hthet

IMPORTANT: This is important
 
  
<<<
 
 